# Generated by Django 4.1.4 on 2023-01-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_customuser_is_admin_customuser_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
