# Generated by Django 4.1.4 on 2023-01-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='father name'),
        ),
    ]
