# Generated by Django 4.1.4 on 2023-01-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_customuser_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждение'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='Отчество'),
        ),
    ]
