# Generated by Django 4.1.4 on 2023-01-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_customuser_is_teacher_alter_customuser_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='classes',
            field=models.CharField(blank=True, help_text='Класс для ученика или классы, которые обучает учитель, если много, пишется через пробел', max_length=254, verbose_name='Классы'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subjects',
            field=models.CharField(blank=True, default='', help_text='Предметы, которые преподаёт учитель, если ученик - оставить пустым', max_length=254, verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(blank=True, default='', help_text='Если отчества нет, оставьте поле пустым', max_length=254, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Отметье, если пользователь считается учителем', verbose_name='Учитель'),
        ),
    ]
