# Generated by Django 4.1.4 on 2023-03-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_customuser_classes_customuser_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classes',
            field=models.CharField(blank=True, default='', help_text='Класс для ученика или классы, которые обучает учитель, если много, пишется через пробел', max_length=254, verbose_name='Классы'),
        ),
    ]
