# Generated by Django 4.1.4 on 2022-12-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_marks_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='marktype',
            field=models.CharField(choices=[('1', 'Домашняя работа'), ('2', 'Классная работа'), ('3', 'Самостоятельная работа'), ('4', 'Контрольная работа'), ('5', 'Административная контрольная работа')], default='2', max_length=50),
        ),
    ]
