# Generated by Django 4.1.4 on 2023-01-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='work',
        ),
        migrations.AddField(
            model_name='work',
            name='fullwork',
            field=models.TextField(max_length=500, verbose_name='Полное описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='shortwork',
            field=models.TextField(max_length=100, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
