# Generated by Django 4.1.4 on 2023-01-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_work_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='fullwork',
            new_name='fulldesk',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='shortwork',
            new_name='shortdesk',
        ),
    ]
